### ISSUE TITLE
PHP version confusion

### ISSUE THREAD

**Issue by speich** [php/pecl-database-oci8#18]
I'm confused. Here on github it says that current version also works for php8.3:
_Use pecl install oci8 to install for PHP 8.2 and PHP 8.3._

, but on PECL https://pecl.php.net/package/oci8 it says:
_Use 'pecl install oci8' to install for PHP 8.2._

Which one is correct ?

Also, when can I expect oci8 for php8.4 ?

**Comment by cjbj** [comment]
PECL has the released packages.

GitHub is the development area for unreleased code, which may be in flux and/or inconsistent.

I was hoping to release OCI8 3.4 this week, but am waiting for some testing to be completed. It's unclear when that will be completed.  If you have run tests, please let me know the configuration and results.

**Comment by speich** [comment]
Thanks for the clarification. I'm just asking because I'm planing to upgrade from PHP8.1 to 8.3 or if possible to 8.4, but need to be able to connect with OCI8.

**Comment by cjbj** [comment]
@speich the proposed OCI8 3.4 version installs fine for me with PHP 8.4 built from the current PHP master branch.  Since OCI8 3.4 will release before PHP 8.4 is finalized, I can't update the README to say it is supported - because a PHP change may break it.

**Comment by cjbj** [comment]
PHP OCI8 3.4 is out.  Give it whirl on PHP 8.4 and let us know if you uncover anything.

**Comment by kumiech** [comment]
PHP OCI8 3.4 doesnt work with my local environment. 

Server version: Apache/2.4.54 (Win64)

`PHP 8.4.1 (cli) (built: Nov 20 2024 11:13:22) (NTS Visual C++ 2022 x64)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans`

`OCI8 Support => enabled
OCI8 DTrace Support => disabled
OCI8 Version => 3.4.0
Oracle Run-time Client Library Version => 21.15.0.0.0
Oracle Compile-time Instant Client Version => 23.6

Directive => Local Value => Master Value
oci8.max_persistent => -1 => -1
oci8.persistent_timeout => -1 => -1
oci8.ping_interval => 60 => 60
oci8.privileged_connect => Off => Off
oci8.statement_cache_size => 20 => 20
oci8.default_prefetch => 100 => 100
oci8.old_oci_close_semantics => Off => Off
oci8.connection_class => no value => no value
oci8.events => Off => Off
oci8.prefetch_lob_size => 0 => 0

Statistics =>
Active Persistent Connections => 0
Active Connections => 0`

On my application I've got message`Call to undefined function oci_connect()` and error in logfile
`04-Dec-2024 11:45:26 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_oci8_19.dll' (tried: C:/laragon/bin/php/php-8.4.1-nts-Win32-vs17-x64/ext\php_oci8_19.dll (Nie można odnaleźć określonego modułu), C:/laragon/bin/php/php-8.4.1-nts-Win32-vs17-x64/ext\php_php_oci8_19.dll.dll (Nie można odnaleźć określonego modułu)) in Unknown on line 0`

**Comment by cmb69** [comment]
I assume that you used php.exe to get the `-v` and `-i` output. In that case OCI.dll is likely not in the PATH when you run Apache. Do `where OCI.dll`, and copy the DLL into the apache/bin folder. Then restart httpd.exe.
