### ISSUE TITLE
Tests fail in 3.4 PECL release

### ISSUE THREAD

**Issue by datadestroyd** [php/pecl-database-oci8#22]
I just tested the new 3.4 release from PECL, but there are some issues with the tests. First of all, all tests bork because `skipifconnectfailure.inc` is not present in the tarball. After fixing that, I get two failing tests: `bind_misccoltypes_errs_21.phpt` and `bind_number_21.phpt`. They both seem to have a copy-paste error: the error message patterns look for `bind_misccoltypes_errs.php` and `bind_number.php` instead of `bind_misccoltypes_errs_21.php` and `bind_number_21.php`, respectively (the `_21` is missing).

**Comment by cjbj** [comment]
Thanks for taking time to report the problems.

I've added that file to package.xml so it will be in a future release.  

I no longer have access to my full test harness, so if you want to submit a PR for the 21c changes, please do so.

**Comment by datadestroyd** [comment]
Thank you for the quick reply. I will send a PR soon.

**Comment by cjbj** [comment]
@datadestroyd thank you - I've merged the PR
