### ISSUE TITLE
Tests not compatible with Instant Client 23

### ISSUE THREAD

**Issue by datadestroyd** [php/pecl-database-oci8#7]
I just tried to build the OCI8 module with Instant Client 23, but I got 68 failing tests. It appears Oracle changed most/all of the error messages. They now include a help link on a separate line. Here is an example from `array_bind_001.diff`:

```
001+ Warning: oci_bind_array_by_name(): OCI-21560: argument at position 3 is null, invalid, or out of range
002+ Help: https://docs.oracle.com/error-help/db/oci-21560/ in /tmp/tmp.c3TEAcQZbp/p/oci8-2.2.0/tests/array_bind_001.php on line 48
001- Warning: oci_bind_array_by_name(): OCI-21560: argument 3 is null, invalid, or out of range in %s on line %d
```

**Comment by cjbj** [comment]
Try `export ORA_SUPPRESS_ERROR_URL=TRUE`

**Comment by datadestroyd** [comment]
@cjbj Thank you, that helped a lot! I am now down to 6 failing tests. Some error messages have changed slightly. I would be willing to prepare a PR to make the tests compatible with the new version.

**Comment by cjbj** [comment]
Check the latest changes.  They are passing with Oracle Database 23ai for me.  

Thanks for reporting the problem
